-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'


hl.bind("SUPER" .. " + " .. "T", hl.dsp.exec_cmd("kitty"))

hl.bind("SUPER" .. " + " .. "F", hl.dsp.exec_cmd("firefox"))

hl.bind("ALT" .. " + " .. "TAB", hl.dsp.window.cycle_next())

hl.bind("ALT" .. " + " .. "SPACE", hl.dsp.window.fullscreen())

hl.bind("ALT" .. " + " .. "L", hl.dsp.focus({ workspace = "+1" }))

hl.bind("ALT" .. " + " .. "H", hl.dsp.focus({ workspace = -1 }))

hl.bind("ALT + CONTROL" .. " + " .. "L", hl.dsp.window.move("+1"))

hl.bind("ALT + CONTROL" .. " + " .. "H", hl.dsp.window.move(-1))

hl.bind("ALT + SHIFT" .. " + " .. "L", hl.dsp.window.move("+1", { follow = false }))

hl.bind("ALT + SHIFT" .. " + " .. "H", hl.dsp.window.move(-1, { follow = false }))

hl.monitor({
    output   = "HDMI-A-2",
    mode     = "1366x768@59.79",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@60.02",
    position = "1366x0",
    scale    = 1.5,
})

hl.window_rule({
    name  = "float",
    match = {
        class = "^(firefox)$",
        title = "^(Extension:)(.*)$",
    },
    float = true,
})

hl.window_rule({
    name  = "stayfocused",
    match = {
        class = "^(firefox)$",
        title = "^(Extension:)(.*)$",
    },
    stay_focused = true,
})

hl.window_rule({
    name  = "noborder",
    match = {
        class = "^(firefox)$",
        title = "^(Extension:)(.*)$",
    },
    border = false,
})

hl.window_rule({
    name  = "float",
    match = {
        class = "^(firefox)$",
        title = "^$",
    },
    float = true,
})

hl.window_rule({
    name  = "noborder",
    match = {
        class = "^(firefox)$",
        title = "^$",
    },
    border = false,
})
